### ISSUE TITLE
[BUG] [CCI] Running `yo-doc` and `yo-component` scripts crashes with an error

### ISSUE THREAD

**Issue by andreymyssak** [opensearch-project/oui#598]
**Describe the bug**

Running `yo-doc` and `yo-component` scripts crashes with the following error
```
$ yo ./generator-oui/app/documentation.js
internal/modules/cjs/loader.js:1131
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/trim-newlines/index.js
require() of ES modules is not supported.
require() of /Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/trim-newlines/index.js from /Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/meow/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/trim-newlines/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/trim-newlines/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1131:13)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/andreymyssak/Gomasko/Projects/opensearch/oui/node_modules/meow/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.

```

**To Reproduce**
1. Open project
2. Run `yarn yo-doc` or `yarn yo-component`
4. See the error

**Expected behavior**
Generation of files according to scripts

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura v13.2
 - Node v14.21.3
 - Yarn v1.22.19

**Comment by BSFishy** [comment]
PR has been merged into main :+1:
